### ISSUE TITLE
Seller: Available to sell

### ISSUE THREAD

**Issue by Taticherie1** [Taticherie1/icecreamtruck#19]
Seller Requirement: When user selects “Available to sell” their location should automatically appear on the map. They don’t need to enter address.

**Comment by NirajRaval** [comment]
as per our Skype discussion. on the web, we can't able to get the location .

**Comment by Taticherie1** [comment]
According to the discussion, you understood that the button 'Available to sell' makes sellers appear on the map. Is there still confusion? @NirajRaval
<img width="787" alt="screen shot 2018-06-03 at 9 23 39 am" src="https://user-images.githubusercontent.com/38584712/40887020-f090f3ca-670f-11e8-8d46-2e66524ef9f5.png">
